#!/usr/bin/env python3
"""Build PNG plots from CSV exports produced by the Java application."""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import Iterable

import matplotlib.pyplot as plt
import pandas as pd


SUPPORTED_FILES = (
    "sin",
    "ln",
    "log2",
    "log3",
    "log5",
    "cos",
    "tan",
    "cot",
    "sec",
    "csc",
    "system",
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Plot graphs from CSV files with columns x,result."
    )
    parser.add_argument(
        "--input-dir",
        default="output",
        help="Directory with CSV files generated by the Java application.",
    )
    parser.add_argument(
        "--output-dir",
        default="plots",
        help="Directory where PNG files will be saved.",
    )
    return parser.parse_args()


def load_csv(csv_path: Path) -> pd.DataFrame:
    """Read CSV and normalize the data for plotting."""
    frame = pd.read_csv(csv_path)
    required_columns = {"x", "result"}
    missing_columns = required_columns.difference(frame.columns)
    if missing_columns:
        missing = ", ".join(sorted(missing_columns))
        raise ValueError(f"CSV {csv_path} is missing required columns: {missing}")

    frame = frame.copy()
    frame["x"] = pd.to_numeric(frame["x"], errors="coerce")
    frame["result"] = pd.to_numeric(frame["result"], errors="coerce")
    frame = frame.sort_values("x")

    # Replace infinities with NaN so matplotlib does not connect discontinuities.
    frame["result"] = frame["result"].replace([float("inf"), float("-inf")], pd.NA)
    return frame


def plot_file(csv_path: Path, png_path: Path) -> None:
    """Plot one CSV file and save the result as PNG."""
    frame = load_csv(csv_path)

    plt.figure(figsize=(10, 6))
    plt.plot(frame["x"], frame["result"], linewidth=1.8, color="#0b6e4f")
    plt.title(f"Graph for {csv_path.stem}")
    plt.xlabel("x")
    plt.ylabel("result")
    plt.grid(True, linestyle="--", alpha=0.5)
    plt.tight_layout()
    plt.savefig(png_path, dpi=150)
    plt.close()


def iter_expected_csv(input_dir: Path) -> Iterable[tuple[Path, Path]]:
    """Yield known CSV/PNG pairs in a stable order."""
    for stem in SUPPORTED_FILES:
        csv_path = input_dir / f"{stem}.csv"
        png_path = Path(f"{stem}.png")
        yield csv_path, png_path


def main() -> int:
    args = parse_args()
    input_dir = Path(args.input_dir)
    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    print(f"Reading CSV files from: {input_dir.resolve()}")
    print(f"Saving PNG files to: {output_dir.resolve()}")

    for csv_path, png_name in iter_expected_csv(input_dir):
        if not csv_path.exists():
            print(f"Skipping missing file: {csv_path}")
            continue

        try:
            png_path = output_dir / png_name
            plot_file(csv_path, png_path)
            print(f"Saved plot: {png_path}")
        except Exception as error:  # noqa: BLE001
            print(f"Failed to plot {csv_path}: {error}")

    print("Done.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
